/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pos.forms.stocks;

import com.pos.beans.Customer;
import com.pos.beans.User;
import com.pos.forms.loginform.loginservice.LoginService;
import com.pos.forms.stocks.stocksservice.StocksService;
import com.pos.forms.welcome.WelcomeForm;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbidAli
 */
public class StocksForm extends javax.swing.JFrame {
    List<Customer> listOfCustomers;
    /**
     * Creates new form StocksForm
     */
    public StocksForm() {
        initComponents();
        showCustomersInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_Customers = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_CustomerId = new javax.swing.JTextField();
        txt_CustomerName = new javax.swing.JTextField();
        txt_CustomerCnic = new javax.swing.JTextField();
        txt_CustomerMobileNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Customers = new javax.swing.JTable();
        btn_CustomerInsert = new javax.swing.JButton();
        btn_CustomerUpdate = new javax.swing.JButton();
        btn_CustomerDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_CustomerAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        tab_Customers.addTab("Products", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        tab_Customers.addTab("Suppliers", jPanel2);

        jLabel1.setText("ID :");

        jLabel2.setText("Name :");

        jLabel3.setText("CNIC :");

        jLabel4.setText("Mobile No. :");

        jLabel5.setText("Address :");

        txt_CustomerId.setEditable(false);

        tbl_Customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "CNIC", "Mobile No.", "Address"
            }
        ));
        tbl_Customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Customers);

        btn_CustomerInsert.setText("Insert");
        btn_CustomerInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomerInsertActionPerformed(evt);
            }
        });

        btn_CustomerUpdate.setText("Update");
        btn_CustomerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomerUpdateActionPerformed(evt);
            }
        });

        btn_CustomerDelete.setText("Delete");
        btn_CustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomerDeleteActionPerformed(evt);
            }
        });

        txt_CustomerAddress.setColumns(20);
        txt_CustomerAddress.setRows(5);
        jScrollPane2.setViewportView(txt_CustomerAddress);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_CustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txt_CustomerCnic)
                            .addComponent(txt_CustomerMobileNo)
                            .addComponent(txt_CustomerId)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_CustomerInsert)
                        .addGap(18, 18, 18)
                        .addComponent(btn_CustomerUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btn_CustomerDelete)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_CustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_CustomerCnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_CustomerMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_CustomerInsert)
                            .addComponent(btn_CustomerUpdate)
                            .addComponent(btn_CustomerDelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(237, 237, 237))
        );

        tab_Customers.addTab("Customers", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_Customers))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_Customers)
        );

        tab_Customers.getAccessibleContext().setAccessibleName("Customers");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CustomerInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomerInsertActionPerformed

        if(txt_CustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Customers,"Invalid Customer Name");

        }
        
         else
         {
        
           Customer customer = new Customer();
           customer.setCustomerName(txt_CustomerName.getText());
           customer.setCnic(txt_CustomerCnic.getText());
           customer.setAddress(txt_CustomerAddress.getText());
           customer.setMobileNo(txt_CustomerMobileNo.getText());
           StocksService service  = new StocksService();
           if(service.insertCustomer(customer))
           {
              System.out.println("customer inserted succefully : " + customer.getCustomerName());
              showCustomersInTable();
              JOptionPane.showMessageDialog(tab_Customers,"Customer Inserted Successfully .");
              clearCustomerFormFields();
                         
           }
           else
           {
                JOptionPane.showMessageDialog(tab_Customers,"Customer Insertion Failed.");
                clearCustomerFormFields();
           }
           
         }
           
        
    }//GEN-LAST:event_btn_CustomerInsertActionPerformed

    private void tbl_CustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CustomersMouseClicked
        int index = tbl_Customers.getSelectedRow();
        showCustomerInFormFields(index);
    }//GEN-LAST:event_tbl_CustomersMouseClicked

    private void btn_CustomerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomerUpdateActionPerformed
      if(!txt_CustomerId.getText().equals(""))
      {
        
        if(txt_CustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Customers,"Invalid Customer Name");

        }
        
         else
         {
        
           Customer customer = new Customer();
           customer.setCustomerId(Long.parseLong(txt_CustomerId.getText()));
           customer.setCustomerName(txt_CustomerName.getText());
           customer.setCnic(txt_CustomerCnic.getText());
           customer.setAddress(txt_CustomerAddress.getText());
           customer.setMobileNo(txt_CustomerMobileNo.getText());
           StocksService service  = new StocksService();
           if(service.updateCustomer(customer))
           {
              System.out.println("customer updated succefully : " + customer.getCustomerName());
              showCustomersInTable();
              JOptionPane.showMessageDialog(tab_Customers,"Customer updated Successfully .");
              clearCustomerFormFields();
                         
           }
           else
           {
                JOptionPane.showMessageDialog(tab_Customers,"Customer updation Failed.");
                clearCustomerFormFields();
           }
           
         }
      }
    }//GEN-LAST:event_btn_CustomerUpdateActionPerformed

    private void btn_CustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomerDeleteActionPerformed
        int index = tbl_Customers.getSelectedRow();

        showCustomerInFormFields(index);

        if(index >=0)
        {
            Customer customer = new Customer();
            customer.setCustomerId(Long.parseLong(txt_CustomerId.getText()));
            StocksService service  = new StocksService();
            if(service.deleteCustomer(customer))
            {
                System.out.println("customer deleted succefully : " + customer.getCustomerId());
                showCustomersInTable();
                clearCustomerFormFields();
                JOptionPane.showMessageDialog(tab_Customers,"Customer deleted Successfully .");

            }
            else
            {
                JOptionPane.showMessageDialog(tab_Customers,"Customer deletion Failed.");
                clearCustomerFormFields();
            }
        }
    }//GEN-LAST:event_btn_CustomerDeleteActionPerformed
private void clearCustomerFormFields() {
        
                txt_CustomerId.setText("");
                txt_CustomerAddress.setText("");
                txt_CustomerCnic.setText("");
                txt_CustomerMobileNo.setText("");
                txt_CustomerName.setText("");
    }

  public void showCustomersInTable()
    {
        StocksService service  = new StocksService();
        listOfCustomers = service.fetchCustomersList();
        DefaultTableModel model = (DefaultTableModel)tbl_Customers.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[5];
        for(int i = 0; i < listOfCustomers.size(); i++)
        {
            row[0] = listOfCustomers.get(i).getCustomerId();
            row[1] = listOfCustomers.get(i).getCustomerName();
            row[2] = listOfCustomers.get(i).getCnic();
            row[3] = listOfCustomers.get(i).getMobileNo();
            row[4] = listOfCustomers.get(i).getAddress();
            
            
            model.addRow(row);
        }
    }
    private void showCustomerInFormFields(int index) {
               
        if(index >= 0)
        {
            txt_CustomerId.setText(listOfCustomers.get(index).getCustomerId()+ "");
            txt_CustomerCnic.setText(listOfCustomers.get(index).getCnic());
            txt_CustomerMobileNo.setText(listOfCustomers.get(index).getMobileNo());
            txt_CustomerName.setText(listOfCustomers.get(index).getCustomerName());
            txt_CustomerAddress.setText(listOfCustomers.get(index).getAddress());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StocksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StocksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StocksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StocksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StocksForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CustomerDelete;
    private javax.swing.JButton btn_CustomerInsert;
    private javax.swing.JButton btn_CustomerUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tab_Customers;
    private javax.swing.JTable tbl_Customers;
    private javax.swing.JTextArea txt_CustomerAddress;
    private javax.swing.JTextField txt_CustomerCnic;
    private javax.swing.JTextField txt_CustomerId;
    private javax.swing.JTextField txt_CustomerMobileNo;
    private javax.swing.JTextField txt_CustomerName;
    // End of variables declaration//GEN-END:variables

  

    
}
