/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pos.forms.stocks;

import com.mysql.jdbc.StringUtils;
import com.pos.beans.Customer;
import com.pos.beans.Products;
import com.pos.beans.Supplier;
import com.pos.beans.User;
import com.pos.forms.loginform.loginservice.LoginService;
import com.pos.forms.stocks.stocksservice.StocksService;
import com.pos.forms.welcome.WelcomeForm;
import com.pos.utils.DBUtils;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author AbidAli
 */
public class StocksForm extends javax.swing.JFrame {
    List<Customer> listOfCustomers;
    List<Supplier> listOfSuppliers;
    List<Products> listOfProducts;
    private TableRowSorter sorter;
    private TableRowSorter sorterCustomer;
    private TableRowSorter sorterProducts;
    Vector<Long> idsVectorOfSuppliers = new Vector<Long>();
    
    /**
     * Creates new form StocksForm
     */
    public StocksForm() {
        initComponents();
        showCustomersInTable();
        showSuppliersInTable();
        showProductsInTable();
        addDocumentListnerForSearchFields();
        DBUtils.addItemsToCombo(cmb_Suppliers, listOfSuppliers, "Select Suppiler", idsVectorOfSuppliers);
        System.out.println(idsVectorOfSuppliers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_Stocks = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_Products = new javax.swing.JTable();
        txt_SearchFieldProducts = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_ProductName = new javax.swing.JTextField();
        txt_ProductId = new javax.swing.JTextField();
        txt_ProductPurchasingPrice = new javax.swing.JTextField();
        txt_ProductSellingPrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_ProductQuanitiyAtHand = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmb_Suppliers = new javax.swing.JComboBox();
        btn_ResetProducts = new javax.swing.JButton();
        btn_ProductsInsert = new javax.swing.JButton();
        btn_ProductUpdate = new javax.swing.JButton();
        btn_ProductDelete = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_BarCodeField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_SupplierId = new javax.swing.JTextField();
        txt_SupplierName = new javax.swing.JTextField();
        txt_SupplierMobileNo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Suppliers = new javax.swing.JTable();
        btn_SupplierInsert = new javax.swing.JButton();
        btn_SupplierUpdate = new javax.swing.JButton();
        btn_SupplierDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_SupplierAddress = new javax.swing.JTextArea();
        btn_Reset = new javax.swing.JButton();
        txt_SearchField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_CustomerId = new javax.swing.JTextField();
        txt_CustomerName = new javax.swing.JTextField();
        txt_CustomerCnic = new javax.swing.JTextField();
        txt_CustomerMobileNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Customers = new javax.swing.JTable();
        btn_CustomerInsert = new javax.swing.JButton();
        btn_CustomerUpdate = new javax.swing.JButton();
        btn_CustomerDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_CustomerAddress = new javax.swing.JTextArea();
        btn_ResetCustomers = new javax.swing.JButton();
        txt_SearchCustomer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_Products.setAutoCreateRowSorter(true);
        tbl_Products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Purchasing Price", "Selling Price", "Supplier", "Quantity at hand", "Barcode"
            }
        ));
        tbl_Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ProductsMouseClicked(evt);
            }
        });
        sorterProducts = new TableRowSorter<>(tbl_Products.getModel());
        tbl_Products.setRowSorter(sorterProducts);
        jScrollPane5.setViewportView(tbl_Products);

        jLabel12.setText("Search :");

        jLabel13.setText("Product Id:");

        jLabel14.setText("Product Name :");

        jLabel15.setText("Purchasing Price:");

        txt_ProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProductNameActionPerformed(evt);
            }
        });

        txt_ProductId.setEditable(false);

        txt_ProductPurchasingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProductPurchasingPriceActionPerformed(evt);
            }
        });

        txt_ProductSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProductSellingPriceActionPerformed(evt);
            }
        });

        jLabel16.setText("Selling Price:");

        txt_ProductQuanitiyAtHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProductQuanitiyAtHandActionPerformed(evt);
            }
        });

        jLabel17.setText("Quantity at hand:");

        jLabel18.setText("Supplier:");

        btn_ResetProducts.setText("Reset");
        btn_ResetProducts.setToolTipText("");
        btn_ResetProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetProductsActionPerformed(evt);
            }
        });

        btn_ProductsInsert.setText("Insert");
        btn_ProductsInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductsInsertActionPerformed(evt);
            }
        });

        btn_ProductUpdate.setText("Update");
        btn_ProductUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductUpdateActionPerformed(evt);
            }
        });

        btn_ProductDelete.setText("Delete");
        btn_ProductDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductDeleteActionPerformed(evt);
            }
        });

        jLabel19.setForeground(java.awt.Color.red);
        jLabel19.setText("*");

        jLabel21.setForeground(java.awt.Color.red);
        jLabel21.setText("*");

        jLabel22.setForeground(java.awt.Color.red);
        jLabel22.setText("*");

        jLabel23.setForeground(java.awt.Color.red);
        jLabel23.setText("*");

        jLabel20.setText("Bar Code:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SearchFieldProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_ProductName)
                                            .addComponent(txt_ProductPurchasingPrice)
                                            .addComponent(txt_ProductId, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(txt_ProductSellingPrice)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_ProductQuanitiyAtHand))
                                            .addComponent(cmb_Suppliers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_BarCodeField))))
                                .addGap(48, 48, 48))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_ProductsInsert)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_ProductUpdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_ProductDelete))
                                    .addComponent(btn_ResetProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_SearchFieldProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProductPurchasingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProductSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProductQuanitiyAtHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cmb_Suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_BarCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(13, 13, 13)
                        .addComponent(btn_ResetProducts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ProductsInsert)
                            .addComponent(btn_ProductUpdate)
                            .addComponent(btn_ProductDelete))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel20.getAccessibleContext().setAccessibleName("Bar Code:");

        tab_Stocks.addTab("Products", jPanel1);

        jLabel6.setText("ID :");

        jLabel7.setText("Name :");

        jLabel9.setText("Mobile No. :");

        jLabel10.setText("Address :");

        txt_SupplierId.setEditable(false);

        txt_SupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SupplierNameActionPerformed(evt);
            }
        });

        tbl_Suppliers.setAutoCreateRowSorter(true);
        tbl_Suppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile No.", "Address"
            }
        ));
        tbl_Suppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SuppliersMouseClicked(evt);
            }
        });
        sorter = new TableRowSorter<>(tbl_Suppliers.getModel());
        tbl_Suppliers.setRowSorter(sorter);
        jScrollPane3.setViewportView(tbl_Suppliers);

        btn_SupplierInsert.setText("Insert");
        btn_SupplierInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SupplierInsertActionPerformed(evt);
            }
        });

        btn_SupplierUpdate.setText("Update");
        btn_SupplierUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SupplierUpdateActionPerformed(evt);
            }
        });

        btn_SupplierDelete.setText("Delete");
        btn_SupplierDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SupplierDeleteActionPerformed(evt);
            }
        });

        txt_SupplierAddress.setColumns(20);
        txt_SupplierAddress.setRows(5);
        jScrollPane4.setViewportView(txt_SupplierAddress);

        btn_Reset.setText("Reset");
        btn_Reset.setToolTipText("");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_SupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txt_SupplierMobileNo)
                            .addComponent(txt_SupplierId)
                            .addComponent(jScrollPane4)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(btn_SupplierInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_SupplierUpdate)
                            .addGap(18, 18, 18)
                            .addComponent(btn_SupplierDelete))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_SupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_SupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_SupplierMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_SupplierInsert)
                            .addComponent(btn_SupplierUpdate)
                            .addComponent(btn_SupplierDelete)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(237, 237, 237))
        );

        jLabel8.setText("Search :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab_Stocks.addTab("Suppliers", jPanel2);

        jLabel1.setText("ID :");

        jLabel2.setText("Name :");

        jLabel3.setText("CNIC :");

        jLabel4.setText("Phone :");

        jLabel5.setText("Address :");

        txt_CustomerId.setEditable(false);

        txt_CustomerCnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CustomerCnicActionPerformed(evt);
            }
        });

        txt_CustomerMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CustomerMobileNoActionPerformed(evt);
            }
        });

        tbl_Customers.setAutoCreateRowSorter(true);
        tbl_Customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "CNIC", "Phone", "Address"
            }
        ));
        tbl_Customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CustomersMouseClicked(evt);
            }
        });
        sorterCustomer = new TableRowSorter<>(tbl_Customers.getModel());
        tbl_Customers.setRowSorter(sorterCustomer);
        jScrollPane1.setViewportView(tbl_Customers);

        btn_CustomerInsert.setText("Insert");
        btn_CustomerInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomerInsertActionPerformed(evt);
            }
        });

        btn_CustomerUpdate.setText("Update");
        btn_CustomerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomerUpdateActionPerformed(evt);
            }
        });

        btn_CustomerDelete.setText("Delete");
        btn_CustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomerDeleteActionPerformed(evt);
            }
        });

        txt_CustomerAddress.setColumns(20);
        txt_CustomerAddress.setRows(5);
        jScrollPane2.setViewportView(txt_CustomerAddress);

        btn_ResetCustomers.setText("Reset");
        btn_ResetCustomers.setToolTipText("");
        btn_ResetCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetCustomersActionPerformed(evt);
            }
        });

        jLabel11.setText("Search :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_CustomerInsert)
                                .addGap(18, 18, 18)
                                .addComponent(btn_CustomerUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btn_CustomerDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel5)))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_CustomerMobileNo)
                                    .addComponent(jScrollPane2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_CustomerName))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(30, 30, 30)
                                        .addComponent(txt_CustomerId))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_CustomerCnic)))))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_ResetCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SearchCustomer)))
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_CustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_SearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_CustomerCnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_CustomerMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ResetCustomers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_CustomerInsert)
                            .addComponent(btn_CustomerUpdate)
                            .addComponent(btn_CustomerDelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tab_Stocks.addTab("Customers", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_Stocks))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_Stocks)
        );

        tab_Stocks.getAccessibleContext().setAccessibleName("Customers");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CustomerInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomerInsertActionPerformed

        if(txt_CustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Invalid Customer Name");

        }
        
         else
         {
        
           Customer customer = new Customer();
           customer.setCustomerName(txt_CustomerName.getText());
           customer.setCnic(txt_CustomerCnic.getText());
           customer.setAddress(txt_CustomerAddress.getText());
           customer.setMobileNo(txt_CustomerMobileNo.getText());
           StocksService service  = new StocksService();
           if(service.insertCustomer(customer))
           {
              System.out.println("customer inserted succefully : " + customer.getCustomerName());
              showCustomersInTable();
              JOptionPane.showMessageDialog(tab_Stocks,"Customer Inserted Successfully .");
              clearCustomerFormFields();
                         
           }
           else
           {
                JOptionPane.showMessageDialog(tab_Stocks,"Customer Insertion Failed.");
                clearCustomerFormFields();
           }
           
         }
           
        
    }//GEN-LAST:event_btn_CustomerInsertActionPerformed

    private void tbl_CustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CustomersMouseClicked
        int index = tbl_Customers.getSelectedRow();
        String custId = tbl_Customers.getModel().getValueAt(tbl_Customers.convertRowIndexToModel(index),0).toString();
        showCustomerInFormFields(custId);
    }//GEN-LAST:event_tbl_CustomersMouseClicked

    private void btn_CustomerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomerUpdateActionPerformed
      if(!txt_CustomerId.getText().equals(""))
      {
        
        if(txt_CustomerName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Invalid Customer Name");

        }
        
         else
         {
        
           Customer customer = new Customer();
           customer.setCustomerId(Long.parseLong(txt_CustomerId.getText()));
           customer.setCustomerName(txt_CustomerName.getText());
           customer.setCnic(txt_CustomerCnic.getText());
           customer.setAddress(txt_CustomerAddress.getText());
           customer.setMobileNo(txt_CustomerMobileNo.getText());
           StocksService service  = new StocksService();
           if(service.updateCustomer(customer))
           {
              System.out.println("customer updated succefully : " + customer.getCustomerName());
              showCustomersInTable();
              JOptionPane.showMessageDialog(tab_Stocks,"Customer updated Successfully .");
              clearCustomerFormFields();
                         
           }
           else
           {
                JOptionPane.showMessageDialog(tab_Stocks,"Customer updation Failed.");
                clearCustomerFormFields();
           }
           
         }
      }
    }//GEN-LAST:event_btn_CustomerUpdateActionPerformed

    private void btn_CustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomerDeleteActionPerformed
        int index = tbl_Customers.getSelectedRow();
        if(index >=0)
        {
            String custId = tbl_Customers.getModel().getValueAt(tbl_Customers.convertRowIndexToModel(index),0).toString();
            showCustomerInFormFields(custId);

            Customer customer = new Customer();
            customer.setCustomerId(Long.parseLong(txt_CustomerId.getText()));
            StocksService service  = new StocksService();
            if(service.deleteCustomer(customer))
            {
                System.out.println("customer deleted succefully : " + customer.getCustomerId());
                showCustomersInTable();
                clearCustomerFormFields();
                JOptionPane.showMessageDialog(tab_Stocks,"Customer deleted Successfully .");

            }
            else
            {
                JOptionPane.showMessageDialog(tab_Stocks,"Customer deletion Failed.");
                clearCustomerFormFields();
            }
        }
    }//GEN-LAST:event_btn_CustomerDeleteActionPerformed

    private void tbl_SuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SuppliersMouseClicked
        // TODO add your handling code here:
        int index = tbl_Suppliers.getSelectedRow();
        String supplierId = tbl_Suppliers.getModel().getValueAt(tbl_Suppliers.convertRowIndexToModel(index),0).toString();
        showSupplierInFormFields(supplierId);
        
    }//GEN-LAST:event_tbl_SuppliersMouseClicked

    private void btn_SupplierInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SupplierInsertActionPerformed
        // TODO add your handling code here:
        
        if(txt_SupplierName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Invalid Supplier Name");

        }
        
         else
         {
        
           Supplier supplier = new Supplier();
           supplier.setSupplierName(txt_SupplierName.getText());
           supplier.setSupplierAddress(txt_SupplierAddress.getText());
           supplier.setSupplierContactNo(txt_SupplierMobileNo.getText());
           StocksService service  = new StocksService();
           if(service.insertSupplier(supplier))
           {
              System.out.println("supplier inserted succefully : " + supplier.getSupplierName());
              showSuppliersInTable();
              JOptionPane.showMessageDialog(tab_Stocks,"Supplier Inserted Successfully .");
              clearSupplierFormFields();
                         
           }
           else
           {
                JOptionPane.showMessageDialog(tab_Stocks,"Supplier Insertion Failed.");
                clearSupplierFormFields();
           }
           
         }
    }//GEN-LAST:event_btn_SupplierInsertActionPerformed

    private void btn_SupplierUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SupplierUpdateActionPerformed
        // TODO add your handling code here:
        if(!txt_SupplierId.getText().equals(""))
      {
        
        if(txt_SupplierName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Invalid Supplier Name");

        }
        
         else
         {
        
           Supplier supplier = new Supplier();
           supplier.setSupplierId(Long.parseLong(txt_SupplierId.getText()));
           supplier.setSupplierName(txt_SupplierName.getText());
           supplier.setSupplierAddress(txt_SupplierAddress.getText());
           supplier.setSupplierContactNo(txt_SupplierMobileNo.getText());
           StocksService service  = new StocksService();
           if(service.updateSupplier(supplier))
           {
              System.out.println("supplier updated succefully : " + supplier.getSupplierName());
              showSuppliersInTable();
              JOptionPane.showMessageDialog(tab_Stocks,"Supplier updated successfuly.");
              clearSupplierFormFields();
                         
           }
           else
           {
                JOptionPane.showMessageDialog(tab_Stocks,"Supplier updation Failed.");
                clearSupplierFormFields();
           }
           
         }
      }
    }//GEN-LAST:event_btn_SupplierUpdateActionPerformed

    private void btn_SupplierDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SupplierDeleteActionPerformed
        // TODO add your handling code here:
         
        int index = tbl_Suppliers.getSelectedRow();
        
        if(index >=0)
        {
            String supplierId = tbl_Suppliers.getModel().getValueAt(tbl_Suppliers.convertRowIndexToModel(index),0).toString();
            showSupplierInFormFields(supplierId);

            Supplier supplier = new Supplier();
            supplier.setSupplierId(Long.parseLong(txt_SupplierId.getText()));
            StocksService service  = new StocksService();
            if(service.deleteSupplier(supplier))
            {
                System.out.println("supplier deleted succefully : " + supplier.getSupplierId());
                showSuppliersInTable();
                clearSupplierFormFields();
                JOptionPane.showMessageDialog(tab_Stocks,"Supplier deleted Successfully .");

            }
            else
            {
                JOptionPane.showMessageDialog(tab_Stocks,"Supplier deletion Failed.");
                clearSupplierFormFields();
            }
        }
    }//GEN-LAST:event_btn_SupplierDeleteActionPerformed

    private void txt_SupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SupplierNameActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        clearSupplierFormFields();
        tbl_Suppliers.clearSelection();
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_ResetCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetCustomersActionPerformed
        // TODO add your handling code here:
        clearCustomerFormFields();
        tbl_Customers.clearSelection();
    }//GEN-LAST:event_btn_ResetCustomersActionPerformed

    private void txt_CustomerCnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CustomerCnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CustomerCnicActionPerformed

    private void txt_CustomerMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CustomerMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CustomerMobileNoActionPerformed

    private void tbl_ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ProductsMouseClicked
        // TODO add your handling code here:
        int index = tbl_Products.getSelectedRow();
        String productId = tbl_Products.getModel().getValueAt(tbl_Products.convertRowIndexToModel(index),0).toString();
        showProductInFormFields(productId);
    }//GEN-LAST:event_tbl_ProductsMouseClicked

    private void txt_ProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProductNameActionPerformed

    private void txt_ProductPurchasingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProductPurchasingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProductPurchasingPriceActionPerformed

    private void txt_ProductSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProductSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProductSellingPriceActionPerformed

    private void txt_ProductQuanitiyAtHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProductQuanitiyAtHandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProductQuanitiyAtHandActionPerformed

    private void btn_ResetProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetProductsActionPerformed
         // TODO add your handling code here:
        clearProductFormFields();
        tbl_Products.clearSelection();
    }//GEN-LAST:event_btn_ResetProductsActionPerformed

    private void btn_ProductsInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductsInsertActionPerformed
  if(txt_ProductName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Please enter product Name");
            txt_ProductName.requestFocusInWindow();
            return;

        }
   if(txt_ProductPurchasingPrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Please enter purchasing price of product");
            txt_ProductPurchasingPrice.requestFocusInWindow();
            return;

        }
   if(txt_ProductQuanitiyAtHand.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Please enter quantity of product.");
            txt_ProductQuanitiyAtHand.requestFocusInWindow();
            return;

        }
  if(txt_ProductSellingPrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Please enter selling price of product.");
            txt_ProductSellingPrice.requestFocusInWindow();
            return;
        }
        
        else
         {
        
           Products product = new Products();
           product.setProductName(txt_ProductName.getText());
           product.setPurchasePrice(Double.parseDouble(txt_ProductPurchasingPrice.getText()));
           product.setPrice(Double.parseDouble(txt_ProductSellingPrice.getText()));
           product.setQuantityAtHand(Long.parseLong(txt_ProductQuanitiyAtHand.getText()));
           Long supplierId = idsVectorOfSuppliers.get(cmb_Suppliers.getSelectedIndex()-1);        //as selected index starts from 1
           product.setSupplierId(supplierId+"");
           product.setBarCode(txt_BarCodeField.getText());
           StocksService service  = new StocksService();
           if(service.insertProduct(product))
           {
              System.out.println("product inserted succefully : " + product.getProductName());
              showProductsInTable();
              JOptionPane.showMessageDialog(tab_Stocks,"Product Inserted Successfully .");
              clearProductFormFields();
                         
           }
           else
           {
                JOptionPane.showMessageDialog(tab_Stocks,"Product Insertion Failed.");
                clearProductFormFields();
           }
           
         }
        
        
    }//GEN-LAST:event_btn_ProductsInsertActionPerformed

    private void btn_ProductUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductUpdateActionPerformed
         // TODO add your handling code here:
   if(!txt_ProductId.getText().equals(""))
      {
        
         if(txt_ProductName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Please enter product Name");
            txt_ProductName.requestFocusInWindow();
            return;

        }
   if(txt_ProductPurchasingPrice.getText().equals("") || txt_ProductPurchasingPrice.getText().equals("0"))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Please enter valid purchasing price of product");
            txt_ProductPurchasingPrice.requestFocusInWindow();
            return;

        }
   if(txt_ProductQuanitiyAtHand.getText().equals(""))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Please enter quantity of product.");
            txt_ProductQuanitiyAtHand.requestFocusInWindow();
            return;

        }
  if(txt_ProductSellingPrice.getText().equals("") || txt_ProductSellingPrice.getText().equals("0"))
        {
            JOptionPane.showMessageDialog(tab_Stocks,"Please enter valid selling price of product.");
            txt_ProductSellingPrice.requestFocusInWindow();
            return;
        }
        
        Double sellingPrice = Double.parseDouble(txt_ProductSellingPrice.getText());
        Double purchasingPrice = Double.parseDouble(txt_ProductPurchasingPrice.getText());
    if(sellingPrice<=purchasingPrice)
    {
        JOptionPane.showMessageDialog(tab_Stocks,"Selling price cannot be less than or equal to purchasing price.");
        txt_ProductSellingPrice.requestFocusInWindow();
        return;
    }
        
     else
         {
        
           Products product = new Products();
           product.setProductId(Long.parseLong(txt_ProductId.getText()));
           product.setProductName(txt_ProductName.getText());
           product.setPrice(Double.parseDouble(txt_ProductSellingPrice.getText()));
           product.setPurchasePrice(Double.parseDouble(txt_ProductPurchasingPrice.getText()));
           product.setQuantityAtHand(Long.parseLong(txt_ProductQuanitiyAtHand.getText()));
            if(cmb_Suppliers.getSelectedIndex() != 0)
            {

                product.setSupplierId(""+idsVectorOfSuppliers.get(cmb_Suppliers.getSelectedIndex()-1));            //extracting please select item -1
            }
           product.setBarCode(txt_BarCodeField.getText());           
           StocksService service  = new StocksService();
           if(service.updateProduct(product))
           {
              System.out.println("product updated succefully : " + product.getProductName());
              showProductsInTable();
              JOptionPane.showMessageDialog(tab_Stocks,"Product updated successfuly.");
              clearProductFormFields();
                         
           }
           else
           {
                JOptionPane.showMessageDialog(tab_Stocks,"Product updation Failed.");
                clearProductFormFields();
           }
           
         }
      }
    }//GEN-LAST:event_btn_ProductUpdateActionPerformed

    private void btn_ProductDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductDeleteActionPerformed
        int index = tbl_Products.getSelectedRow();
        
        if(index >=0)
        {
            String productId = tbl_Products.getModel().getValueAt(tbl_Products.convertRowIndexToModel(index),0).toString();
            showProductInFormFields(productId);

            Products product = new Products();
            product.setProductId(Long.parseLong(txt_ProductId.getText()));
            StocksService service  = new StocksService();
            if(service.deleteProduct(product))
            {
                System.out.println("product deleted succefully : " + product.getProductId());
                showProductsInTable();
                clearProductFormFields();
                JOptionPane.showMessageDialog(tab_Stocks,"Product deleted Successfully .");

            }
            else
            {
                JOptionPane.showMessageDialog(tab_Stocks,"Product deletion Failed.");
                clearProductFormFields();
            }
        }
    }//GEN-LAST:event_btn_ProductDeleteActionPerformed
private void clearCustomerFormFields() {
        
                txt_CustomerId.setText("");
                txt_CustomerAddress.setText("");
                txt_CustomerCnic.setText("");
                txt_CustomerMobileNo.setText("");
                txt_CustomerName.setText("");
                txt_SearchCustomer.setText("");
    }
private void clearSupplierFormFields() {
        
                txt_SupplierId.setText("");
                txt_SupplierAddress.setText("");
                txt_SupplierMobileNo.setText("");
                txt_SupplierName.setText("");
                txt_SearchField.setText("");
    }
  private void showCustomersInTable()
    {
        StocksService service  = new StocksService();
        listOfCustomers = service.fetchCustomersList();
        DefaultTableModel model = (DefaultTableModel)tbl_Customers.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[5];
        for(int i = 0; i < listOfCustomers.size(); i++)
        {
            row[0] = listOfCustomers.get(i).getCustomerId();
            row[1] = listOfCustomers.get(i).getCustomerName();
            row[2] = listOfCustomers.get(i).getCnic();
            row[3] = listOfCustomers.get(i).getMobileNo();
            row[4] = listOfCustomers.get(i).getAddress();
            
            
            model.addRow(row);
        }
    }
  private void showSuppliersInTable()
    {
        StocksService service  = new StocksService();
        listOfSuppliers = service.fetchSupplierList();
        DefaultTableModel model = (DefaultTableModel)tbl_Suppliers.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[5];
        for(int i = 0; i < listOfSuppliers.size(); i++)
        {
            row[0] = listOfSuppliers.get(i).getSupplierId();
            row[1] = listOfSuppliers.get(i).getSupplierName();
            row[2] = listOfSuppliers.get(i).getSupplierContactNo();
            row[3] = listOfSuppliers.get(i).getSupplierAddress();
            
            
            model.addRow(row);
        }
    }
    private void showCustomerInFormFields(String customerId) {
               
         if(customerId != null && !"".equals(customerId) )
        {
            Customer cust = new Customer();
            cust.setCustomerId(Long.parseLong(customerId));
            txt_CustomerId.setText(listOfCustomers.get(listOfCustomers.indexOf(cust)).getCustomerId()+ "");
            txt_CustomerCnic.setText(listOfCustomers.get(listOfCustomers.indexOf(cust)).getCnic());
            txt_CustomerMobileNo.setText(listOfCustomers.get(listOfCustomers.indexOf(cust)).getMobileNo());
            txt_CustomerName.setText(listOfCustomers.get(listOfCustomers.indexOf(cust)).getCustomerName());
            txt_CustomerAddress.setText(listOfCustomers.get(listOfCustomers.indexOf(cust)).getAddress());
        }
    }
    private void showSupplierInFormFields(String suppId) {
               
        if(suppId != null && !"".equals(suppId) )
        {
            Supplier supp = new Supplier();
            supp.setSupplierId(Long.parseLong(suppId));
            txt_SupplierId.setText(listOfSuppliers.get(listOfSuppliers.indexOf(supp)).getSupplierId()+ "");
            txt_SupplierMobileNo.setText(listOfSuppliers.get(listOfSuppliers.indexOf(supp)).getSupplierContactNo());
            txt_SupplierName.setText(listOfSuppliers.get(listOfSuppliers.indexOf(supp)).getSupplierName());
            txt_SupplierAddress.setText(listOfSuppliers.get(listOfSuppliers.indexOf(supp)).getSupplierAddress());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StocksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StocksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StocksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StocksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StocksForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CustomerDelete;
    private javax.swing.JButton btn_CustomerInsert;
    private javax.swing.JButton btn_CustomerUpdate;
    private javax.swing.JButton btn_ProductDelete;
    private javax.swing.JButton btn_ProductUpdate;
    private javax.swing.JButton btn_ProductsInsert;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_ResetCustomers;
    private javax.swing.JButton btn_ResetProducts;
    private javax.swing.JButton btn_SupplierDelete;
    private javax.swing.JButton btn_SupplierInsert;
    private javax.swing.JButton btn_SupplierUpdate;
    private javax.swing.JComboBox cmb_Suppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane tab_Stocks;
    private javax.swing.JTable tbl_Customers;
    private javax.swing.JTable tbl_Products;
    private javax.swing.JTable tbl_Suppliers;
    private javax.swing.JTextField txt_BarCodeField;
    private javax.swing.JTextArea txt_CustomerAddress;
    private javax.swing.JTextField txt_CustomerCnic;
    private javax.swing.JTextField txt_CustomerId;
    private javax.swing.JTextField txt_CustomerMobileNo;
    private javax.swing.JTextField txt_CustomerName;
    private javax.swing.JTextField txt_ProductId;
    private javax.swing.JTextField txt_ProductName;
    private javax.swing.JTextField txt_ProductPurchasingPrice;
    private javax.swing.JTextField txt_ProductQuanitiyAtHand;
    private javax.swing.JTextField txt_ProductSellingPrice;
    private javax.swing.JTextField txt_SearchCustomer;
    private javax.swing.JTextField txt_SearchField;
    private javax.swing.JTextField txt_SearchFieldProducts;
    private javax.swing.JTextArea txt_SupplierAddress;
    private javax.swing.JTextField txt_SupplierId;
    private javax.swing.JTextField txt_SupplierMobileNo;
    private javax.swing.JTextField txt_SupplierName;
    // End of variables declaration//GEN-END:variables

    private void addDocumentListnerForSearchFields() {
        txt_SearchField.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
            search(txt_SearchField.getText());
         }
         @Override
         public void removeUpdate(DocumentEvent e) {
            search(txt_SearchField.getText());
         }
         @Override
         public void changedUpdate(DocumentEvent e) {
            search(txt_SearchField.getText());
         }
         public void search(String str) {
            if (str.length() == 0) {
               sorter.setRowFilter(null);
            } else {
               sorter.setRowFilter(RowFilter.regexFilter(str));
            }
         }

          
      });
        txt_SearchCustomer.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
            search(txt_SearchCustomer.getText());
         }
         @Override
         public void removeUpdate(DocumentEvent e) {
            search(txt_SearchCustomer.getText());
         }
         @Override
         public void changedUpdate(DocumentEvent e) {
            search(txt_SearchCustomer.getText());
         }
         public void search(String str) {
            if (str.length() == 0) {
               sorterCustomer.setRowFilter(null);
            } else {
               sorterCustomer.setRowFilter(RowFilter.regexFilter(str));
            }
         }

          
      });
        
        txt_SearchFieldProducts.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
            search(txt_SearchFieldProducts.getText());
         }
         @Override
         public void removeUpdate(DocumentEvent e) {
            search(txt_SearchFieldProducts.getText());
         }
         @Override
         public void changedUpdate(DocumentEvent e) {
            search(txt_SearchFieldProducts.getText());
         }
         public void search(String str) {
            if (str.length() == 0) {
               sorterProducts.setRowFilter(null);
            } else {
               sorterProducts.setRowFilter(RowFilter.regexFilter(str));
            }
         }

          
      });
    }

    private void showProductsInTable() {
        StocksService service  = new StocksService();
        listOfProducts = service.fetchProductsList();
        DefaultTableModel model = (DefaultTableModel)tbl_Products.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[7];
        for(int i = 0; i < listOfProducts.size(); i++)
        {
            row[0] = listOfProducts.get(i).getProductId();
            row[1] = listOfProducts.get(i).getProductName();
            row[2] = listOfProducts.get(i).getPurchasePrice();
            row[3] = listOfProducts.get(i).getPrice();
            if(!StringUtils.isNullOrEmpty(listOfProducts.get(i).getSupplierId()) && listOfSuppliers!=null && listOfSuppliers.size()>0){
                for (Supplier supplier : listOfSuppliers) {
                    if(supplier.getSupplierId().toString().equals(listOfProducts.get(i).getSupplierId())){
                        row[4] = supplier.getSupplierName();
                        break;
                    }
                }
            } else{
                row[4] = null;
            }
            
            row[5] = listOfProducts.get(i).getQuantityAtHand();
            row[6] = listOfProducts.get(i).getBarCode();
            
            
            model.addRow(row);
        }
    }

    private void clearProductFormFields() {
                txt_ProductId.setText("");
                txt_ProductName.setText("");
                txt_ProductPurchasingPrice.setText("");
                txt_ProductQuanitiyAtHand.setText("");
                txt_ProductSellingPrice.setText("");
                cmb_Suppliers.setSelectedIndex(0);
                txt_BarCodeField.setText("");
    }

    private void showProductInFormFields(String productId) {
        
               
        if(productId != null && !"".equals(productId) )
        {
            Products product = new Products();
            product.setProductId(Long.parseLong(productId));
            txt_ProductId.setText(listOfProducts.get(listOfProducts.indexOf(product)).getProductId()+ "");
            txt_ProductName.setText(listOfProducts.get(listOfProducts.indexOf(product)).getProductName());
            txt_ProductPurchasingPrice.setText(""+listOfProducts.get(listOfProducts.indexOf(product)).getPurchasePrice());
            txt_ProductSellingPrice.setText(""+listOfProducts.get(listOfProducts.indexOf(product)).getPrice());
            txt_ProductQuanitiyAtHand.setText(""+listOfProducts.get(listOfProducts.indexOf(product)).getQuantityAtHand());
            Supplier supp = new Supplier();
            String supplierId = listOfProducts.get(listOfProducts.indexOf(product)).getSupplierId();
            if(supplierId!=null && !"".equals(supplierId))
            {
                supp.setSupplierId(Long.parseLong(supplierId));
            }
            
            cmb_Suppliers.setSelectedIndex(listOfSuppliers.indexOf(supp)+1);        // as please select item is at position 0 thats why +1 is required
            if(listOfProducts.get(listOfProducts.indexOf(product)).getBarCode()!=null)
            {
                txt_BarCodeField.setText(listOfProducts.get(listOfProducts.indexOf(product)).getBarCode());
            }
            else{
                txt_BarCodeField.setText("");
            }
        }
    }

  

    
}
