/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pos.forms.pointofsale;

import com.pos.beans.Customer;
import com.pos.beans.Products;
import com.pos.beans.SaleDetail;
import com.pos.forms.pointofsale.service.PointOfSaleService;
import com.pos.forms.stocks.stocksservice.StocksService;
import com.pos.utils.DBUtils;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbidAli
 */
public class PointOfSaleForm extends javax.swing.JFrame {
    List<Products> listOfProducts;
    List<Customer> listOfCustomers;
    
    /**
     * Creates new form PointOfSaleForm
     */
    public PointOfSaleForm() {
        PointOfSaleService posService = new PointOfSaleService();
        listOfProducts = posService.fetchProductsList();
        
        StocksService stockService = new StocksService();
        listOfCustomers = stockService.fetchCustomersList();
        
        initComponents();
        txt_SaleId.setText(""+(posService.calculateSaleId()+1));
        DBUtils.addItemsToCombo(cmb_Products, listOfProducts, "Select Product");
        DBUtils.addItemsToCombo(cmb_Customer, listOfCustomers, "Select Customer");
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_SalePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_AddToDetail = new javax.swing.JButton();
        txt_SaleId = new javax.swing.JTextField();
        txt_Quantity = new javax.swing.JTextField();
        txt_Price = new javax.swing.JTextField();
        txt_SubTotal = new javax.swing.JTextField();
        cmb_Customer = new javax.swing.JComboBox();
        cmb_Products = new javax.swing.JComboBox();
        pnl_PaymentPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_AmountDue = new javax.swing.JTextField();
        txt_AmountChange = new javax.swing.JTextField();
        txt_AmountPaid = new javax.swing.JTextField();
        btn_AddToDetail1 = new javax.swing.JButton();
        pnl_SaleDetailPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SaleDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_SalePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Sale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setText("Customer :");

        jLabel2.setText("Sale ID :");

        jLabel3.setText("Product :");

        jLabel4.setText("Price :");

        jLabel5.setText("Quantity :");

        jLabel6.setText("Subtotal :");

        btn_AddToDetail.setText("Add To Cart");
        btn_AddToDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddToDetailActionPerformed(evt);
            }
        });

        txt_Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QuantityActionPerformed(evt);
            }
        });
        txt_Quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_QuantityFocusLost(evt);
            }
        });

        txt_Price.setEditable(false);

        txt_SubTotal.setEditable(false);

        cmb_Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_SalePanelLayout = new javax.swing.GroupLayout(pnl_SalePanel);
        pnl_SalePanel.setLayout(pnl_SalePanelLayout);
        pnl_SalePanelLayout.setHorizontalGroup(
            pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Quantity)
                    .addComponent(txt_Price)
                    .addComponent(txt_SaleId)
                    .addComponent(txt_SubTotal)
                    .addComponent(cmb_Products, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Customer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btn_AddToDetail)
                .addContainerGap())
        );
        pnl_SalePanelLayout.setVerticalGroup(
            pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_SalePanelLayout.createSequentialGroup()
                        .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_SaleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_SalePanelLayout.createSequentialGroup()
                                .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl_SalePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(3, 3, 3)))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_SalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl_SalePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(9, 9, 9)))
                                .addGap(18, 18, 18)
                                .addComponent(txt_SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_SalePanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel6)))
                        .addGap(15, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_SalePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_AddToDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pnl_PaymentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel7.setText("Amount Due :");

        jLabel8.setText("Amount Paid :");

        jLabel9.setText("Amount Change :");

        txt_AmountChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AmountChangeActionPerformed(evt);
            }
        });

        txt_AmountPaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_AmountPaidFocusLost(evt);
            }
        });

        btn_AddToDetail1.setText("Add To Cart");
        btn_AddToDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddToDetail1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_PaymentPanelLayout = new javax.swing.GroupLayout(pnl_PaymentPanel);
        pnl_PaymentPanel.setLayout(pnl_PaymentPanelLayout);
        pnl_PaymentPanelLayout.setHorizontalGroup(
            pnl_PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(pnl_PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_AmountChange, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(txt_AmountDue)
                    .addComponent(txt_AmountPaid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddToDetail1)
                .addContainerGap())
        );
        pnl_PaymentPanelLayout.setVerticalGroup(
            pnl_PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_AmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnl_PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_AmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnl_PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txt_AmountChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_AddToDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pnl_SaleDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sale Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        tbl_SaleDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale ID", "Product Name", "Price", "Quantity", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(tbl_SaleDetail);

        javax.swing.GroupLayout pnl_SaleDetailPanelLayout = new javax.swing.GroupLayout(pnl_SaleDetailPanel);
        pnl_SaleDetailPanel.setLayout(pnl_SaleDetailPanelLayout);
        pnl_SaleDetailPanelLayout.setHorizontalGroup(
            pnl_SaleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SaleDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_SaleDetailPanelLayout.setVerticalGroup(
            pnl_SaleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SaleDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_SalePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_PaymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(pnl_SaleDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_SaleDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_SalePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_PaymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddToDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddToDetailActionPerformed
       
        DefaultTableModel model = (DefaultTableModel)tbl_SaleDetail.getModel();
        // clear jtable content
       
        Object[] row = new Object[5];
        
            row[0] = txt_SaleId.getText();
            row[1] = cmb_Products.getSelectedItem();
            row[2] = txt_Price.getText();
            row[3] = txt_Quantity.getText();
            row[4] = txt_SubTotal.getText();
            
            
            model.addRow(row);
            //todo
//            SaleDetail saleDetail = new SaleDetail(Long.parseLong(row[0].toString()), Long.MIN_VALUE, Long.MIN_VALUE, Long.MIN_VALUE);
//            this.saleDetailList.add(new SaleDetail(row[0], ))
            
            Double amountDue = txt_AmountDue.getText().equals("")?0:Double.parseDouble(txt_AmountDue.getText()) ;
            txt_AmountDue.setText((amountDue + Double.parseDouble(txt_SubTotal.getText()))+"");
              
            
            
            cmb_Products.setSelectedIndex(0);
            txt_Price.setText("");
            txt_Quantity.setText("");
            txt_SubTotal.setText("");
            
            
              
        
        
    }//GEN-LAST:event_btn_AddToDetailActionPerformed

    private void txt_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QuantityActionPerformed
       
    }//GEN-LAST:event_txt_QuantityActionPerformed

    private void btn_AddToDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddToDetail1ActionPerformed
        PointOfSaleService posService = new PointOfSaleService();
            
        
//        posService.performSale();     todo
        txt_SaleId.setText(""+(posService.calculateSaleId()+1));
        
    }//GEN-LAST:event_btn_AddToDetail1ActionPerformed

    private void cmb_ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ProductsActionPerformed
      int index =   cmb_Products.getSelectedIndex()-1;  //leave first item title 
      if(index!=-1 && listOfProducts.size()>0)
      {
        Products selectedProduct =  listOfProducts.get(index);
        if(null != selectedProduct)
        {
        txt_Price.setText(selectedProduct.getPrice().toString());
        }
      }
      else
      {
            txt_Price.setText("");
      }
    }//GEN-LAST:event_cmb_ProductsActionPerformed

    private void txt_QuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_QuantityFocusLost
        // TODO add your handling code here:
 // TODO add your handling code here:
       Double price = Double.parseDouble(txt_Price.getText());
       Long quantity = Long.parseLong(txt_Quantity.getText());
       txt_SubTotal.setText((quantity * price)+"");        
        
    }//GEN-LAST:event_txt_QuantityFocusLost

    private void txt_AmountChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AmountChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AmountChangeActionPerformed

    private void txt_AmountPaidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AmountPaidFocusLost
            Double amountPaid = txt_AmountPaid.getText().equals("")?0:Double.parseDouble(txt_AmountPaid.getText()) ;
            txt_AmountChange.setText((amountPaid - Double.parseDouble(txt_AmountDue.getText()))+"");
              
    }//GEN-LAST:event_txt_AmountPaidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PointOfSaleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddToDetail;
    private javax.swing.JButton btn_AddToDetail1;
    private javax.swing.JComboBox cmb_Customer;
    private javax.swing.JComboBox cmb_Products;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_PaymentPanel;
    private javax.swing.JPanel pnl_SaleDetailPanel;
    private javax.swing.JPanel pnl_SalePanel;
    private javax.swing.JTable tbl_SaleDetail;
    private javax.swing.JTextField txt_AmountChange;
    private javax.swing.JTextField txt_AmountDue;
    private javax.swing.JTextField txt_AmountPaid;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_Quantity;
    private javax.swing.JTextField txt_SaleId;
    private javax.swing.JTextField txt_SubTotal;
    // End of variables declaration//GEN-END:variables
}
